version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=tienda_sl
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgres/data
